---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hoops.paulyu.dev
  resources:
  - standings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hoops.paulyu.dev
  resources:
  - standings/finalizers
  verbs:
  - update
- apiGroups:
  - hoops.paulyu.dev
  resources:
  - standings/status
  verbs:
  - get
  - patch
  - update
